import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: [
    {
      path: "./fonts/geist-latin-normal.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/geist-latin-normal.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/geist-latin-normal.woff2",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-geist-sans",
  display: "swap",
  fallback: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
  adjustFontFallback: "Arial",
});

const geistMono = localFont({
  src: [
    {
      path: "./fonts/geist-mono-latin-normal.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/geist-mono-latin-normal.woff2",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-geist-mono",
  display: "swap",
  fallback: ["ui-monospace", "SFMono-Regular", "Consolas", "monospace"],
  adjustFontFallback: "Arial",
});

const newsreader = localFont({
  src: [
    {
      path: "./fonts/newsreader-latin-normal.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/newsreader-latin-normal.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/newsreader-latin-italic.woff2",
      weight: "500",
      style: "italic",
    },
  ],
  variable: "--font-newsreader",
  display: "swap",
  fallback: ["Georgia", "Times New Roman", "serif"],
  adjustFontFallback: "Times New Roman",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${newsreader.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
